NAME: 'EMA Crossover'
MODULE: 'ema_crossover'
CLASS: 'EMAcrossOver'
INTERVAL: '1h'  # 1h
PERIOD: 300
RISK_PC: 1
SIZING: 'risk'
PARAMETERS:
  slow_ema: 50
  fast_ema: 20
  RR: 1.5

# Define pairs to monitor
#WATCHLIST: ['CAD_JPY']
WATCHLIST: ['EUR_USD', 'AUD_USD', 'GBP_USD', 'USD_CAD', 'USD_JPY']
