NAME: 'EMA Crossover'
MODULE: 'ema_crossover'
CLASS: 'EMAcrossOver'
INTERVAL: '30m' # 30m 1h 1d
#PERIOD: 300
#RISK_PC: 1.5
#SIZING: 'risk'

PARAMETERS:
  slow_ema: 50
  fast_ema: 21
  RR: 2.0

# Define pairs to monitor
#WATCHLIST: ['EUR_USD']
WATCHLIST: ['EUR_USD', 'AUD_USD', 'GBP_USD', 'USD_CAD', 'USD_JPY']
