NAME: 'Long EMA Crossover'
MODULE: 'long_ema_crossover'
CLASS: 'LongEMAcrossOver'
INTERVAL: '1h'
#RISK_PC: 1.5

PARAMETERS:
  slow_ema: 20
  fast_ema: 10
  RR: 1

# Define pairs to monitor
WATCHLIST: ['EUR_USD', 'AUD_USD', 'GBP_USD', 'USD_CAD', 'USD_JPY']
