NAME: 'MACD Trend Strategy'
MODULE: 'macd'
CLASS: 'SimpleMACD'
INTERVAL: '1h'
PARAMETERS:
  ema_period: 200
  MACD_fast: 12
  MACD_slow: 26
  MACD_smoothing: 9
  
  # Exit level parameters
  RR: 1.5

#WATCHLIST: ['CAD_JPY', 'EUR_USD', 'AUD_USD', 'GBP_USD', 'EUR_JPY']
WATCHLIST: ['EUR_USD', 'AUD_USD', 'GBP_USD']
            
