NAME: 'SuperTrend Scanner'
MODULE: 'supertrend'
CLASS: 'SuperTrendScan'
INTERVAL: '1d'
PARAMETERS:
  ema_period: 200
  candle_tol: 10
  RR: 2.0
#WATCHLIST: ['CAD_JPY', 'EUR_USD', 'AUD_USD', 'GBP_USD', 'EUR_JPY']
WATCHLIST: ['EUR_USD', 'AUD_USD', 'GBP_USD']
